services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    environment:
      - TZ=Europe/Warsaw
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    volumes:
      - redis_insight_volume_data:/data
    ports:
      - 5540:5540
    environment:
      - TZ=Europe/Warsaw

volumes:
  redis_volume_data:
  redis_insight_volume_data: